/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bundled OpenAPI document (YAML) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI YAML document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/yaml": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bundled OpenAPI document (JSON) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI as JSON */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Failed to serialize YAML to JSON */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and build/data signals */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mechanics/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LCARS / mechanics coverage snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Coverage JSON */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MechanicsCoverageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/combat-effect-spec/officers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Optional LCARS → CombatEffectSpec JSON (local investigation)
         * @description Returns **404** unless `KOBAYASHI_COMBAT_EFFECT_SPEC_DEBUG=1`. LCARS officers must be loaded.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathOfficerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Debug payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Debug disabled or officer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/officers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List officers (optionally roster-filtered) */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                    /** @description When `1` or `true`, only officers present in the profile roster import. */
                    owned_only?: string;
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Officer list envelope */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OfficersListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/officers/{id}/resolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolved officer JSON (LCARS path) */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path: {
                    id: components["parameters"]["PathOfficerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resolved officer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Unknown officer */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ships */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                    owned_only?: string;
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShipsListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ships/{ship_id}/tiers-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tier/level grid and crew slot unlocks for a ship id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ship_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShipTiersLevelsResponse"];
                    };
                };
                /** @description Unknown ship id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hostiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hostiles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HostilesListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data / mechanics version summary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataVersionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forbidden-tech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forbidden/chaos tech catalog for UI */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForbiddenTechCatalogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load merged player profile JSON */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Replace player profile JSON */
        put: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/buildings-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Synced building levels and combat bonuses */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/research-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Synced research and combat bonuses */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List profiles (index) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfilesListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a profile */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProfileRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileEntry"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download profiles tree as zip */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description application/zip bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore profiles tree from Kobayashi export zip (destructive) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/zip": string;
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a profile */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List presets for profile */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresetsListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Save a preset */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Preset"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load one preset */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Preset"];
                    };
                };
                /** @description Preset not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/heuristics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List heuristic seed names */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HeuristicsListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estimate candidate count and wall time */
        get: {
            parameters: {
                query: {
                    ship: string;
                    hostile: string;
                    sims?: number;
                    max_candidates?: number;
                    /** @description Below-decks pool tier — `strict` (combat modifier only — default), `scored` (all below-decks-ability officers ranked by combat relevance with officer power as tiebreaker), or `relaxed` (all officers, ranked by power). Unknown values fall back to strict. */
                    below_decks_pool_mode?: "strict" | "scored" | "relaxed";
                    ship_tier?: number;
                    ship_level?: number;
                    below_decks_slots?: number;
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OptimizeEstimateResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/status/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll async optimize job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: components["parameters"]["PathJobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OptimizeStatusResponse"];
                    };
                };
                /** @description Unknown job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE progress stream until job completes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: components["parameters"]["PathJobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream of JSON event payloads */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request cancellation of async optimize job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: components["parameters"]["PathJobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roster sync file status for profile */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/ingress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** STFC Community Mod sync batch (JSON array) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "stfc-sync-token"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SyncIngressBatch"];
                };
            };
            responses: {
                /** @description Per-type batch results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Body is not a JSON array */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid or missing sync token for persistence */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/officers/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import officers (CSV or Spock JSON) */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "text/csv": string;
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
                /** @description Parse/validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Monte Carlo simulation for one crew */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SimulateRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulateResponse"];
                    };
                };
                /** @description Invalid JSON or validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description CPU saturated */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare/crews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Monte Carlo distributions for 2–5 crews */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompareCrewsRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompareCrewsResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stat-level Δ-on-outcome sensitivity analysis (paired CRN Monte Carlo)
         * @description For a fixed scenario (crew + ship + research + hostile + profile + support buffs),
         *     perturbs each stat in the catalog by a per-stat δ and measures how the outcome
         *     metric changes. Uses paired Common Random Numbers (same seed sequence for baseline
         *     and perturbed runs) so per-seed differences cancel most of the variance. Returns one
         *     row per stat with a 95% confidence interval on the paired mean difference; rows
         *     whose CI excludes zero are flagged `significant: true`.
         *     Synchronous v1 — long runs are gated by the process-wide CPU admission semaphore.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SensitivityRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SensitivityResponse"];
                    };
                };
                /** @description Validation or parse error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensitivity/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Default per-stat δ catalog (15 stats)
         * @description Returns the default δ each stat is perturbed by when the request body omits an override.
         *     `multiplicative: true` means the engine applies `value *= 1 + δ`; `false` means
         *     `value += δ`. UI uses this to format the override input appropriately.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SensitivityDefaultsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensitivity/morris": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Morris-method screening sensitivity (random trajectories, μ\*\/σ)
         * @description Walks `r` random trajectories through stat space (cumulative perturbations applied in
         *     random order). Each trajectory yields one elementary effect (EE) per stat via paired
         *     CRN Monte Carlo at each `k+1` step. Aggregates across trajectories into per-stat
         *     **μ\*** (importance, mean of `|EE|`), **μ** (signed direction), and **σ** (interaction
         *     signal — high σ relative to μ\* means the stat's effect depends on other stats).
         *     Screening method: σ flags interactions but does not identify specific pairs.
         *     Synchronous — gated by the CPU admission semaphore. Compute is `r × (k+1) × num_sims`.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MorrisSensitivityRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MorrisSensitivityResponse"];
                    };
                };
                /** @description Validation or parse error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensitivity/morris/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Morris defaults (δ catalog + r/sims defaults & caps) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MorrisSensitivityDefaultsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensitivity/sobol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sobol variance-based sensitivity (Saltelli design, Jansen estimators)
         * @description Decomposes the variance of the outcome metric into per-stat contributions.
         *     Reports **S_i** (first-order: main effect alone), **S_T_i** (total-order:
         *     main + all interactions involving i), and **interaction strength** (S_T_i − S_i).
         *     v1 ships first-order and total-order indices; per-pair S_ij is planned (Sobol
         *     pairwise needs `N × k(k−1)/2` more evaluations).
         *     Synchronous — gated by the CPU admission semaphore.
         *     Compute is `N × (k + 2)` engine calls (`N=512`, `k=18` → ~10k sims by default).
         */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SobolSensitivityRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SobolSensitivityResponse"];
                    };
                };
                /** @description Validation or parse error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensitivity/sobol/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sobol defaults (δ catalog + N defaults & caps) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SobolSensitivityDefaultsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synchronous crew optimization */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OptimizeRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OptimizeResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/replay-seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deterministic replay of one MC draw (combat trace) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReplaySeedRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start async optimization (same JSON as /api/optimize) */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OptimizeRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OptimizeStartResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CpuBusyError: {
            /** @constant */
            status: "error";
            /** @constant */
            code: "cpu_busy";
            message: string;
            retry_after_ms?: number;
        };
        OkMessageResponse: {
            status: string;
            message?: string;
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
            service: string;
            build: {
                cargo_pkg_version: string;
                git_sha_short?: string | null;
            };
            server: {
                started_at_utc: string;
                max_concurrent_cpu_jobs: number;
                max_concurrent_cpu_jobs_from_env: boolean;
                cpu_job_permits_available: number;
                cpu_job_permits_total: number;
                cpu_job_queue_wait_ms: number | null;
                cpu_job_queue_wait_ms_from_env: boolean;
            };
            data: {
                officer_count: number;
                hostile_data_version?: string | null;
                ship_data_version?: string | null;
                hostile_index_loaded: boolean;
                ship_index_loaded: boolean;
            };
        };
        MechanicsCoverageResponse: {
            /** @constant */
            status: "ok";
            lcars_effects: {
                implemented: number;
            } & {
                [key: string]: unknown;
            };
            ship_hull_abilities: {
                [key: string]: unknown;
            };
            hostile_catalog_entries: {
                [key: string]: unknown;
            };
            fidelity_backlog: ({
                rank: number;
                area: string;
                summary: string;
            } & {
                [key: string]: unknown;
            })[];
        };
        DataVersionResponse: {
            officer_version?: string | null;
            hostile_version?: string | null;
            ship_version?: string | null;
            mechanics: {
                name: string;
                status: string;
            }[];
        };
        OfficersListResponse: {
            officers: ({
                id: string;
                name: string;
                slot?: string | null;
            } & {
                [key: string]: unknown;
            })[];
        };
        ShipsListResponse: {
            ships: ({
                id: string;
                ship_name: string;
                ship_class: string;
                tier?: number;
                level?: number;
            } & {
                [key: string]: unknown;
            })[];
        };
        HostilesListResponse: {
            hostiles: ({
                id: string;
                hostile_name: string;
                display_name?: string;
                level: number;
                ship_class: string;
            } & {
                [key: string]: unknown;
            })[];
        };
        ShipTiersLevelsResponse: {
            tiers: number[];
            levels: number[];
            crew_slots?: {
                [key: string]: unknown;
            }[];
        };
        ForbiddenTechCatalogResponse: {
            items: {
                [key: string]: unknown;
            }[];
        };
        ProfilesListResponse: {
            profiles: components["schemas"]["ProfileEntry"][];
            default_id?: string | null;
        };
        ProfileEntry: {
            id: string;
            name: string;
            sync_token: string;
        };
        CreateProfileRequest: {
            id?: string;
            name: string;
        };
        PresetsListResponse: {
            presets: ({
                id: string;
                name: string;
                ship: string;
                scenario: string;
                schema_version: number;
            } & {
                [key: string]: unknown;
            })[];
        };
        Preset: {
            schema_version: number;
            id: string;
            name: string;
            ship: string;
            scenario: string;
            crew: {
                [key: string]: unknown;
            };
            provenance: {
                [key: string]: unknown;
            };
        };
        HeuristicsListResponse: {
            seeds: string[];
        };
        OptimizeEstimateResponse: {
            estimated_candidates: number;
            sims_per_crew: number;
            estimated_seconds: number;
        };
        OptimizeStartResponse: {
            job_id: string;
        };
        OptimizeStatusResponse: {
            status: string;
            progress?: number;
            crews_done?: number;
            total_crews?: number;
            phase?: string;
            throughput_crews_per_sec?: number;
            eta_seconds?: number;
            progress_preview?: {
                [key: string]: unknown;
            }[];
            /** @description Present when status is done; same shape as synchronous /api/optimize response */
            result?: {
                [key: string]: unknown;
            };
            error?: string;
        };
        OptimizeResponse: {
            status: string;
            engine: string;
            scenario: {
                [key: string]: unknown;
            };
            recommendations: {
                [key: string]: unknown;
            }[];
            duration_ms?: number;
            notes: string[];
            approximate_notes?: string[];
            warnings?: string[];
        };
        /** @description JSON null means empty slot */
        NullableString: string | null;
        SimulateCrew: {
            captain?: components["schemas"]["NullableString"];
            bridge?: components["schemas"]["NullableString"][];
            below_deck?: components["schemas"]["NullableString"][];
        };
        SimulateRequest: {
            ship: string;
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            crew: components["schemas"]["SimulateCrew"];
            num_sims?: number;
            /** Format: int64 */
            seed?: number;
            below_decks_slots?: number;
            support_buffs?: string[];
            chain?: components["schemas"]["ChainGrindRequestDto"];
            defender_opponent?: string;
            /** @description Optional LCARS crew for the defending combatant (merged with hostile ship abilities in PvE). Same shape as `crew`. Non-empty `captain` required when any bridge or below_deck slot is set; omitted or empty = defender officers from hostile data only. */
            defender_crew?: components["schemas"]["SimulateCrew"];
            /** @description Player defender ship id (ships_extended). Mutually exclusive with `hostile`. Requires `defender_profile_id` (opponent account profile, not the attacker profile header). */
            defender_ship?: string;
            defender_ship_tier?: number;
            defender_ship_level?: number;
            /** @description Opponent profile id when `defender_ship` is set. */
            defender_profile_id?: string;
        };
        SimulateStats: {
            win_rate: number;
            stall_rate: number;
            loss_rate: number;
            avg_hull_remaining: number;
            avg_defender_hull_remaining: number;
            n: number;
            win_rate_95_ci?: number[];
        };
        SimulateResponse: {
            status: string;
            stats: components["schemas"]["SimulateStats"];
            /** Format: int64 */
            seed: number;
            warnings?: string[];
        };
        SensitivityRequest: {
            /** @description Ship id (e.g. `uss_enterprise_d`). */
            ship: string;
            /** @description Hostile id or normalized name+level. */
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            captain?: string;
            bridge?: string[];
            below_decks?: string[];
            support_buffs?: string[];
            /** @description Profile id (header / query also accepted). */
            profile_id?: string;
            /** @description Paired sims per stat (also used for the baseline). Clamped server-side. */
            num_sims?: number;
            /** Format: int64 */
            seed?: number;
            rounds?: number;
            /**
             * @description Outcome scalar each stat's Δ is measured against. Default `hull_remaining`.
             * @enum {string}
             */
            metric?: "hull_remaining" | "win_rate" | "rounds_to_kill" | "defender_hull_remaining";
            /**
             * @description Per-stat δ overrides. Keys are stat names (snake_case). A value of `0.0`
             *     skips that stat from the report. Missing keys use the default δ catalog.
             */
            deltas?: {
                [key: string]: number;
            };
        };
        SensitivityRow: {
            stat: string;
            delta_applied: number;
            /** @description Mean of `(perturbed - baseline)` per-seed metric values. */
            mean_diff: number;
            /** @description mean_diff / baseline_mean. Null when baseline is zero or non-finite. */
            mean_diff_relative?: number | null;
            ci95_low: number;
            ci95_high: number;
            /** @description True iff the 95% CI excludes zero. */
            significant: boolean;
        };
        SensitivityResponse: {
            metric: string;
            baseline_mean: number;
            num_sims: number;
            /** Format: int64 */
            base_seed: number;
            rows: components["schemas"]["SensitivityRow"][];
        };
        SensitivityDefaultsResponse: {
            deltas: {
                stat: string;
                delta: number;
                multiplicative: boolean;
            }[];
        };
        MorrisSensitivityRequest: {
            ship: string;
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            captain?: string;
            bridge?: string[];
            below_decks?: string[];
            support_buffs?: string[];
            profile_id?: string;
            /** @description Paired sims per trajectory point. Clamped server-side. */
            num_sims?: number;
            /** @description Number of Morris trajectories. Clamped server-side. */
            r_trajectories?: number;
            /** Format: int64 */
            seed?: number;
            rounds?: number;
            /** @enum {string} */
            metric?: "hull_remaining" | "win_rate" | "rounds_to_kill" | "defender_hull_remaining";
            /**
             * @description Per-stat δ overrides. Keys are stat names (snake_case). A value of `0.0`
             *     drops the stat from the trajectory entirely. Missing keys use defaults.
             */
            deltas?: {
                [key: string]: number;
            };
        };
        MorrisSensitivityRow: {
            stat: string;
            delta_applied: number;
            /** @description Mean of `|EE|` across trajectories. Importance. */
            mu_star: number;
            /** @description Mean signed EE. Direction. */
            mu: number;
            /**
             * @description Sample std of EE across trajectories. High σ relative to μ\* indicates the
             *     stat's effect depends on other previously-perturbed stats (interaction).
             */
            sigma: number;
            n_samples: number;
            mu_star_ci95_low: number;
            mu_star_ci95_high: number;
        };
        MorrisSensitivityResponse: {
            metric: string;
            num_sims_per_point: number;
            r_trajectories: number;
            k_stats: number;
            /** Format: int64 */
            base_seed: number;
            /** Format: int64 */
            total_sims: number;
            rows: components["schemas"]["MorrisSensitivityRow"][];
        };
        MorrisSensitivityDefaultsResponse: {
            deltas: {
                stat: string;
                delta: number;
                multiplicative: boolean;
            }[];
            r_trajectories_default: number;
            r_trajectories_max: number;
            num_sims_default: number;
            num_sims_max: number;
        };
        SobolSensitivityRequest: {
            ship: string;
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            captain?: string;
            bridge?: string[];
            below_decks?: string[];
            support_buffs?: string[];
            profile_id?: string;
            /** @description Samples per Saltelli matrix. Clamped server-side. */
            n_samples?: number;
            /** Format: int64 */
            seed?: number;
            rounds?: number;
            /** @enum {string} */
            metric?: "hull_remaining" | "win_rate" | "rounds_to_kill" | "defender_hull_remaining";
            /**
             * @description Per-stat **base δ** overrides. Each u_i ∈ [0, 1] from the Saltelli matrix
             *     is mapped to a perturbation δ_i ∈ [0, 2 · base_δ_i]. A `0.0` override
             *     drops the stat from the analysis entirely.
             */
            deltas?: {
                [key: string]: number;
            };
        };
        SobolSensitivityRow: {
            stat: string;
            base_delta: number;
            /** @description First-order Sobol index (main effect alone). */
            s1: number;
            /** @description Total-order Sobol index (main + all interactions involving this stat). */
            st: number;
            /**
             * @description `S_T_i − S_i` — fraction of variance from interactions between this stat
             *     and any other. Per-pair S_ij is not estimated in v1.
             */
            interaction: number;
            s1_ci95_low: number;
            s1_ci95_high: number;
            st_ci95_low: number;
            st_ci95_high: number;
        };
        SobolSensitivityResponse: {
            metric: string;
            n_samples: number;
            k_stats: number;
            /** Format: int64 */
            base_seed: number;
            /** Format: int64 */
            total_sims: number;
            /** @description Estimated Var(Y) for the run (sanity check). */
            output_variance: number;
            rows: components["schemas"]["SobolSensitivityRow"][];
        };
        SobolSensitivityDefaultsResponse: {
            deltas: {
                stat: string;
                delta: number;
                multiplicative: boolean;
            }[];
            n_samples_default: number;
            n_samples_max: number;
        };
        CompareCrewsRequest: {
            ship: string;
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            crews: components["schemas"]["SimulateCrew"][];
            num_sims?: number;
            /** Format: int64 */
            seed?: number;
            below_decks_slots?: number;
            proc_sample_trials?: number;
            support_buffs?: string[];
            defender_opponent?: string;
            defender_crew?: components["schemas"]["SimulateCrew"];
            defender_ship?: string;
            defender_ship_tier?: number;
            defender_ship_level?: number;
            defender_profile_id?: string;
        };
        CompareCrewsResponse: {
            status: string;
            /** Format: int64 */
            seed: number;
            crews: {
                [key: string]: unknown;
            }[];
            using_placeholder_combatants: boolean;
            warnings?: string[];
        };
        OfficerGroupConstraintDto: {
            officers: string[];
            min_count: number;
        };
        OptimizeConstraintsDto: {
            must_include?: string[];
            exclude?: string[];
            groups?: components["schemas"]["OfficerGroupConstraintDto"][];
            captain_must_be?: string;
            bridge_must_include?: string[];
            below_decks_must_include?: string[];
        };
        WarmStartCrewDto: {
            captain: string;
            bridge: string[];
            below_decks: string[];
        };
        ChainGrindRequestDto: {
            enabled?: boolean;
            kills_target?: number;
            secondary?: string;
        };
        OptimizeRequest: {
            ship: string;
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            sims?: number;
            /** Format: int64 */
            seed?: number;
            max_candidates?: number;
            strategy?: string;
            /**
             * @description Below-decks pool tier. `strict` (default): combat-modifier-only below-decks officers. `scored`: all below-decks-ability officers ranked by combat relevance (combat → ambiguous → economy-only) with officer power as tiebreaker. `relaxed`: all eligible officers ranked by power. Unknown values fall back to strict.
             * @enum {string}
             */
            below_decks_pool_mode?: "strict" | "scored" | "relaxed";
            heuristics_seeds?: string[];
            heuristics_only?: boolean;
            fast_discovery?: boolean;
            below_decks_strategy?: string;
            analytical_prefilter_keep?: number;
            tiered_scout_sims?: number;
            tiered_top_k?: number;
            tiered_scout_uniform?: boolean;
            /** @description Tiered: when set, scales down per-top-K confirmation iterations so their sum does not exceed floor(mult * tiered_top_k * sims). Exhaustive two-phase: same cap on the width-based confirmation pass for the top exhaustive_scout_top_keep crews. Omit for no global cap (default). Typical values 1.5–3; must be in (0, 20]. */
            tiered_confirm_budget_cap_mult?: number;
            /** @description Exhaustive strategy only; must be sent together with exhaustive_scout_top_keep. Scout-phase Monte Carlo trials per remaining candidate after analytical prefilter; then full `sims` run only on the top exhaustive_scout_top_keep crews by scout ranking. */
            exhaustive_scout_sims?: number;
            /** @description Exhaustive strategy only; paired with exhaustive_scout_sims. How many top scout-ranked crews receive the full per-crew simulation_count (others keep scout statistics). */
            exhaustive_scout_top_keep?: number;
            warm_start_crews?: components["schemas"]["WarmStartCrewDto"][];
            below_decks_slots?: number;
            constraints?: components["schemas"]["OptimizeConstraintsDto"];
            support_buffs?: string[];
            chain?: components["schemas"]["ChainGrindRequestDto"];
            defender_opponent?: string;
            /** @description Optional LCARS crew for the defending combatant (merged with hostile ship abilities). Same shape as simulate `defender_crew`. Ignored when `strategy` is `genetic` (request fails validation). */
            defender_crew?: components["schemas"]["SimulateCrew"];
            /** @description Fixed opponent player ship for PvP (mutually exclusive with `hostile`). Optimize searches attacker crews only. Requires `defender_profile_id`. */
            defender_ship?: string;
            defender_ship_tier?: number;
            defender_ship_level?: number;
            defender_profile_id?: string;
            novelty_lambda?: number;
            novelty_diverse_top?: number;
            novelty_pool?: number;
            /** @description When true with novelty_lambda, crews from optimize_history for this profile + optimize_cache_key (matching chain fingerprint) are treated as redundancy anchors for MMR; they are not added as recommendations. */
            novelty_history_anchors?: boolean;
            /** @description Opaque client fingerprint (e.g. workspace warm-start key). When set and the request runs with an active profile, the server may load matching `optimize_history.json` rows for Monte Carlo reuse (tiered / exhaustive two-phase) and for analytical matchup priors (reference crews from history only; same chain fingerprint as this request’s `chain`). */
            optimize_cache_key?: string;
        };
        ReplaySeedCrew: {
            captain?: components["schemas"]["NullableString"];
            bridge?: components["schemas"]["NullableString"][];
            below_deck?: components["schemas"]["NullableString"][];
        };
        ReplaySeedRequest: {
            ship: string;
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            /** Format: int64 */
            seed?: number;
            /** Format: int64 */
            sim_index: number;
            max_trace_events?: number;
            crew: components["schemas"]["ReplaySeedCrew"];
            support_buffs?: string[];
            defender_opponent?: string;
        };
        SyncIngressBatch: {
            [key: string]: unknown;
        }[];
        ValidationIssue: {
            field?: string;
            messages?: string[];
        };
        ValidationErrorResponse: {
            status?: string;
            message?: string;
            errors?: components["schemas"]["ValidationIssue"][];
        };
    };
    responses: never;
    parameters: {
        /** @description Profile id (alternative to X-Profile-Id) */
        QueryProfile: string;
        HeaderProfileId: string;
        PathOfficerId: string;
        PathJobId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
