/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bundled OpenAPI document (YAML) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI YAML document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/yaml": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bundled OpenAPI document (JSON) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI as JSON */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Failed to serialize YAML to JSON */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and build/data signals */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mechanics/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LCARS / mechanics coverage snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Coverage JSON */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MechanicsCoverageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/combat-effect-spec/officers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Optional LCARS → CombatEffectSpec JSON (local investigation)
         * @description Returns **404** unless `KOBAYASHI_COMBAT_EFFECT_SPEC_DEBUG=1`. LCARS officers must be loaded.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["PathOfficerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Debug payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Debug disabled or officer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/officers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List officers (optionally roster-filtered) */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                    /** @description When `1` or `true`, only officers present in the profile roster import. */
                    owned_only?: string;
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Officer list envelope */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OfficersListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/officers/{id}/resolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolved officer JSON (LCARS path) */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path: {
                    id: components["parameters"]["PathOfficerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resolved officer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Unknown officer */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ships */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                    owned_only?: string;
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShipsListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ships/{ship_id}/tiers-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tier/level grid and crew slot unlocks for a ship id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ship_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShipTiersLevelsResponse"];
                    };
                };
                /** @description Unknown ship id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hostiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hostiles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HostilesListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data / mechanics version summary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataVersionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forbidden-tech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forbidden/chaos tech catalog for UI */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForbiddenTechCatalogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load merged player profile JSON */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Replace player profile JSON */
        put: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/buildings-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Synced building levels and combat bonuses */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/research-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Synced research and combat bonuses */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List profiles (index) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfilesListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a profile */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProfileRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileEntry"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download profiles tree as zip */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description application/zip bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore profiles tree from Kobayashi export zip (destructive) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/zip": string;
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a profile */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List presets for profile */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresetsListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Save a preset */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Preset"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load one preset */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Preset"];
                    };
                };
                /** @description Preset not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/heuristics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List heuristic seed names */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HeuristicsListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estimate candidate count and wall time */
        get: {
            parameters: {
                query: {
                    ship: string;
                    hostile: string;
                    sims?: number;
                    max_candidates?: number;
                    /** @description When "true"/"1", relaxed below-decks search (wide BD pools; heuristic seeds keep officers without combat-only below-decks-slot abilities). Omitted or false = strict default. */
                    allow_below_decks_without_combat_ability?: string;
                    /**
                     * @deprecated
                     * @description Deprecated. Prefer `allow_below_decks_without_combat_ability`. When only this legacy key is present, `prioritize=false` maps to relaxed mode and `prioritize=true` to strict.
                     */
                    prioritize_below_decks_ability?: string;
                    ship_tier?: number;
                    ship_level?: number;
                    below_decks_slots?: number;
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OptimizeEstimateResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/status/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll async optimize job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: components["parameters"]["PathJobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OptimizeStatusResponse"];
                    };
                };
                /** @description Unknown job */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE progress stream until job completes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: components["parameters"]["PathJobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream of JSON event payloads */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request cancellation of async optimize job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: components["parameters"]["PathJobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roster sync file status for profile */
        get: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/ingress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** STFC Community Mod sync batch (JSON array) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "stfc-sync-token"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SyncIngressBatch"];
                };
            };
            responses: {
                /** @description Per-type batch results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Body is not a JSON array */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid or missing sync token for persistence */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/officers/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import officers (CSV or Spock JSON) */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "text/csv": string;
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkMessageResponse"];
                    };
                };
                /** @description Parse/validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Monte Carlo simulation for one crew */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SimulateRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulateResponse"];
                    };
                };
                /** @description Invalid JSON or validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description CPU saturated */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare/crews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Monte Carlo distributions for 2–5 crews */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompareCrewsRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompareCrewsResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synchronous crew optimization */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OptimizeRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OptimizeResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/replay-seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deterministic replay of one MC draw (combat trace) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReplaySeedRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimize/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start async optimization (same JSON as /api/optimize) */
        post: {
            parameters: {
                query?: {
                    /** @description Profile id (alternative to X-Profile-Id) */
                    profile?: components["parameters"]["QueryProfile"];
                };
                header?: {
                    "X-Profile-Id"?: components["parameters"]["HeaderProfileId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OptimizeRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OptimizeStartResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CpuBusyError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CpuBusyError: {
            /** @constant */
            status: "error";
            /** @constant */
            code: "cpu_busy";
            message: string;
            retry_after_ms?: number;
        };
        OkMessageResponse: {
            status: string;
            message?: string;
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
            service: string;
            build: {
                cargo_pkg_version: string;
                git_sha_short?: string | null;
            };
            server: {
                started_at_utc: string;
                max_concurrent_cpu_jobs: number;
                max_concurrent_cpu_jobs_from_env: boolean;
                cpu_job_permits_available: number;
                cpu_job_permits_total: number;
                cpu_job_queue_wait_ms: number | null;
                cpu_job_queue_wait_ms_from_env: boolean;
            };
            data: {
                officer_count: number;
                hostile_data_version?: string | null;
                ship_data_version?: string | null;
                hostile_index_loaded: boolean;
                ship_index_loaded: boolean;
            };
        };
        MechanicsCoverageResponse: {
            /** @constant */
            status: "ok";
            lcars_effects: {
                implemented: number;
            } & {
                [key: string]: unknown;
            };
            ship_hull_abilities: {
                [key: string]: unknown;
            };
            hostile_catalog_entries: {
                [key: string]: unknown;
            };
            fidelity_backlog: ({
                rank: number;
                area: string;
                summary: string;
            } & {
                [key: string]: unknown;
            })[];
        };
        DataVersionResponse: {
            officer_version?: string | null;
            hostile_version?: string | null;
            ship_version?: string | null;
            mechanics: {
                name: string;
                status: string;
            }[];
        };
        OfficersListResponse: {
            officers: ({
                id: string;
                name: string;
                slot?: string | null;
            } & {
                [key: string]: unknown;
            })[];
        };
        ShipsListResponse: {
            ships: ({
                id: string;
                ship_name: string;
                ship_class: string;
                tier?: number;
                level?: number;
            } & {
                [key: string]: unknown;
            })[];
        };
        HostilesListResponse: {
            hostiles: ({
                id: string;
                hostile_name: string;
                display_name?: string;
                level: number;
                ship_class: string;
            } & {
                [key: string]: unknown;
            })[];
        };
        ShipTiersLevelsResponse: {
            tiers: number[];
            levels: number[];
            crew_slots?: {
                [key: string]: unknown;
            }[];
        };
        ForbiddenTechCatalogResponse: {
            items: {
                [key: string]: unknown;
            }[];
        };
        ProfilesListResponse: {
            profiles: components["schemas"]["ProfileEntry"][];
            default_id?: string | null;
        };
        ProfileEntry: {
            id: string;
            name: string;
            sync_token: string;
        };
        CreateProfileRequest: {
            id?: string;
            name: string;
        };
        PresetsListResponse: {
            presets: ({
                id: string;
                name: string;
                ship: string;
                scenario: string;
                schema_version?: number;
            } & {
                [key: string]: unknown;
            })[];
        };
        Preset: {
            schema_version?: number;
            id: string;
            name: string;
            ship: string;
            scenario: string;
            crew: {
                [key: string]: unknown;
            };
            provenance?: {
                [key: string]: unknown;
            };
        };
        HeuristicsListResponse: {
            seeds: string[];
        };
        OptimizeEstimateResponse: {
            estimated_candidates: number;
            sims_per_crew: number;
            estimated_seconds: number;
        };
        OptimizeStartResponse: {
            job_id: string;
        };
        OptimizeStatusResponse: {
            status: string;
            progress?: number;
            crews_done?: number;
            total_crews?: number;
            phase?: string;
            throughput_crews_per_sec?: number;
            eta_seconds?: number;
            progress_preview?: {
                [key: string]: unknown;
            }[];
            /** @description Present when status is done; same shape as synchronous /api/optimize response */
            result?: {
                [key: string]: unknown;
            };
            error?: string;
        };
        OptimizeResponse: {
            status: string;
            engine: string;
            scenario: {
                [key: string]: unknown;
            };
            recommendations: {
                [key: string]: unknown;
            }[];
            duration_ms?: number;
            notes: string[];
            approximate_notes?: string[];
            warnings?: string[];
        };
        /** @description JSON null means empty slot */
        NullableString: string | null;
        SimulateCrew: {
            captain?: components["schemas"]["NullableString"];
            bridge?: components["schemas"]["NullableString"][];
            below_deck?: components["schemas"]["NullableString"][];
        };
        SimulateRequest: {
            ship: string;
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            crew: components["schemas"]["SimulateCrew"];
            num_sims?: number;
            /** Format: int64 */
            seed?: number;
            below_decks_slots?: number;
            support_buffs?: string[];
            chain?: components["schemas"]["ChainGrindRequestDto"];
            defender_opponent?: string;
        };
        SimulateStats: {
            win_rate: number;
            stall_rate: number;
            loss_rate: number;
            avg_hull_remaining: number;
            avg_defender_hull_remaining: number;
            n: number;
            win_rate_95_ci?: number[];
        };
        SimulateResponse: {
            status: string;
            stats: components["schemas"]["SimulateStats"];
            /** Format: int64 */
            seed: number;
            warnings?: string[];
        };
        CompareCrewsRequest: {
            ship: string;
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            crews: components["schemas"]["SimulateCrew"][];
            num_sims?: number;
            /** Format: int64 */
            seed?: number;
            below_decks_slots?: number;
            proc_sample_trials?: number;
            support_buffs?: string[];
            defender_opponent?: string;
        };
        CompareCrewsResponse: {
            status: string;
            /** Format: int64 */
            seed: number;
            crews: {
                [key: string]: unknown;
            }[];
            using_placeholder_combatants: boolean;
            warnings?: string[];
        };
        OfficerGroupConstraintDto: {
            officers: string[];
            min_count: number;
        };
        OptimizeConstraintsDto: {
            must_include?: string[];
            exclude?: string[];
            groups?: components["schemas"]["OfficerGroupConstraintDto"][];
            captain_must_be?: string;
            bridge_must_include?: string[];
            below_decks_must_include?: string[];
        };
        WarmStartCrewDto: {
            captain: string;
            bridge: string[];
            below_decks: string[];
        };
        ChainGrindRequestDto: {
            enabled?: boolean;
            kills_target?: number;
            secondary?: string;
        };
        OptimizeRequest: {
            ship: string;
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            sims?: number;
            /** Format: int64 */
            seed?: number;
            max_candidates?: number;
            strategy?: string;
            /** @description When true, relaxed below-decks behavior (wide BD officer pools; heuristic seeds do not strip economy-only below-decks-slot picks). Omitted or false = strict default (narrow pools; combat heuristic on heuristic seeds). */
            allow_below_decks_without_combat_ability?: boolean;
            /**
             * @deprecated
             * @description Legacy. Prefer `allow_below_decks_without_combat_ability`. When the new field is absent, `prioritize_below_decks_ability` is interpreted as its inverse for backward compatibility.
             */
            prioritize_below_decks_ability?: boolean;
            heuristics_seeds?: string[];
            heuristics_only?: boolean;
            fast_discovery?: boolean;
            below_decks_strategy?: string;
            analytical_prefilter_keep?: number;
            tiered_scout_sims?: number;
            tiered_top_k?: number;
            tiered_scout_uniform?: boolean;
            /** @description Tiered: when set, scales down per-top-K confirmation iterations so their sum does not exceed floor(mult * tiered_top_k * sims). Exhaustive two-phase: same cap on the width-based confirmation pass for the top exhaustive_scout_top_keep crews. Omit for no global cap (default). Typical values 1.5–3; must be in (0, 20]. */
            tiered_confirm_budget_cap_mult?: number;
            /** @description Exhaustive strategy only; must be sent together with exhaustive_scout_top_keep. Scout-phase Monte Carlo trials per remaining candidate after analytical prefilter; then full `sims` run only on the top exhaustive_scout_top_keep crews by scout ranking. */
            exhaustive_scout_sims?: number;
            /** @description Exhaustive strategy only; paired with exhaustive_scout_sims. How many top scout-ranked crews receive the full per-crew simulation_count (others keep scout statistics). */
            exhaustive_scout_top_keep?: number;
            warm_start_crews?: components["schemas"]["WarmStartCrewDto"][];
            below_decks_slots?: number;
            constraints?: components["schemas"]["OptimizeConstraintsDto"];
            support_buffs?: string[];
            chain?: components["schemas"]["ChainGrindRequestDto"];
            defender_opponent?: string;
            novelty_lambda?: number;
            novelty_diverse_top?: number;
            novelty_pool?: number;
            /** @description When true with novelty_lambda, crews from optimize_history for this profile + optimize_cache_key (matching chain fingerprint) are treated as redundancy anchors for MMR; they are not added as recommendations. */
            novelty_history_anchors?: boolean;
            /** @description Opaque client fingerprint (e.g. workspace warm-start key). When set and the request runs with an active profile, the server may load matching `optimize_history.json` rows for Monte Carlo reuse (tiered / exhaustive two-phase) and for analytical matchup priors (reference crews from history only; same chain fingerprint as this request’s `chain`). */
            optimize_cache_key?: string;
        };
        ReplaySeedCrew: {
            captain?: components["schemas"]["NullableString"];
            bridge?: components["schemas"]["NullableString"][];
            below_deck?: components["schemas"]["NullableString"][];
        };
        ReplaySeedRequest: {
            ship: string;
            hostile: string;
            ship_tier?: number;
            ship_level?: number;
            /** Format: int64 */
            seed?: number;
            /** Format: int64 */
            sim_index: number;
            max_trace_events?: number;
            crew: components["schemas"]["ReplaySeedCrew"];
            support_buffs?: string[];
            defender_opponent?: string;
        };
        SyncIngressBatch: {
            [key: string]: unknown;
        }[];
        ValidationIssue: {
            field?: string;
            messages?: string[];
        };
        ValidationErrorResponse: {
            status?: string;
            message?: string;
            errors?: components["schemas"]["ValidationIssue"][];
        };
    };
    responses: never;
    parameters: {
        /** @description Profile id (alternative to X-Profile-Id) */
        QueryProfile: string;
        HeaderProfileId: string;
        PathOfficerId: string;
        PathJobId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
